M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-08-29T14:18:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-29T14:18:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X148.905Y-93.76
T2
X169.905Y-93.76
T3
X98.76Y-115.57
X98.82Y-65.43
X181.18Y-115.6
X181.2Y-70.9
M30
